### PR TITLE
Helidon 2.0: Features carousel and vertical centering

### PR DESCRIPTION
**Pull request by Torrus168**
Signed-off-by: Andrej Kornilov <andrej.kornilov@gmail.com>

### CODE REVIEW

**Comment by m0mus** [comment]
This work is created by my son. I guided him through the process and did a preliminary code review. He will sign OCA when PR is approved.

**Comment by Torrus168** [comment]
@romain-grecourt, all comments addressed. OCA is signed and sent to Oracle. Thanks for reviewing!

**Pull request merged**
